# This file defines the 'call_db_specialist' tool for the Hub agent.
# The actual implementation would need to be a script that makes an RPC call
# to the 'db_specialist_process' MCP server.

name = "call_db_specialist"
prompt = "Calling the Database Specialist Agent with the task: {{.Args}}"

# In a real implementation, the 'exec' would trigger a client-side script
# that knows how to communicate with the db_specialist_process.
# exec = "node /path/to/rpc_client.js db_specialist_process '{{.Args}}'"
